### ISSUE TITLE
Collect COMBAWA_PROJECT_MACHINE_NAME and COMBAWA_PROJECT_NAME variables

### ISSUE THREAD

**Issue by Artusamak** [Happyculture/kumquat_scaffolder#2]
Combawa was collecting the two mentionned parameters but don't use them anymore. So it should live in Kumquat codebase.
One commit on Combawa will remove those parameters collection. It should be brought into this codebase to be consistent and avoid regressions.

**Comment by DuaelFr** [comment]
Those settings were used as helpers. We don't really need them anymore.
