### ISSUE TITLE
Adjust package philosophy

### ISSUE THREAD

**Issue by Artusamak** [Happyculture/kumquat_scaffolder#6]
We should have a philosophy adjustment on this package. There is an assumption that the command is run once at the beginning of a project and in no other use cases. But... it happens that you don't want everything at first (no profile, no admin theme...) and that later on during a project life, you identify the need for an admin theme for instance.

The command should be interactive and ask feature per feature if you want to generate it. (It could be 4 commands and a 5th that navigates through those features).

**Comment by DuaelFr** [comment]
Done
